//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorBooks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;



    public partial class Book
    {

        public int BookId { get; set; }

        [Required(ErrorMessage = "please Enter valid Name")]
        [RegularExpression(@"^[A-Za-z ]*$", ErrorMessage = "Alphabet only")]


        public string BookName { get; set; }

        [Required(ErrorMessage = "plese enter valid book ISBN no")]

        public string BookISBN { get; set; }

        [Required(ErrorMessage = "Date of Joining can't be Empty")]

        public string DateOfPublish { get; set; }

        [Required(ErrorMessage = "Please select Author")]

        public Nullable<int> AuthorId { get; set; }
        public string Photo { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
